### ISSUE TITLE
Timeline for cross-domain support for $.ajax

### ISSUE THREAD

**Issue by jkonowitch** [tirejs/tire#15]
Hello -

I am really interested in using this library, but I need CORS. Any sense of a timeline for inclusion in this library?

Thanks!

**Comment by frozzare** [comment]
Thank you for your interest. We could add CORS support to the next version (1.2.0). It's due this month.

**Comment by jkonowitch** [comment]
Appreciate the response! Great - let me know if I can help. Also, I'm glad you all have built this. There wasn't a lightweight js lib that I saw which had majority browser support, but that also judiciously chose which features to implement. Very cool!

**Comment by caromill** [comment]
@jkonowitch We are discussing the CORS implementation right now. We are really concerned about the limited support in IE8/9: [XDomainRequest - Restrictions, Limitations and Workarounds](https://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx?Redirected=true). We don't want to add a lot of code that will only partly work due to those limitations. What's your opinion on the matter? Is it worth adding the XDomainRequest support?

**Comment by caromill** [comment]
@jkonowitch By the way, thanks for the support and kind words. Much appreciated! :+1:

**Comment by jkonowitch** [comment]
@caromill Hmm. From a value perspective, yes, I think it is really valuable to be able to say, "Tire.js - everything works with IE8/9" IE8 is becoming less of an issue, but it still matters for at least the next year.

That being said, architecturally it makes things a bit tricky. According to that article, IE8/9 CORS supports a very narrow subset of normal ajax functionality. This - `4. Only text/plain is supported for the request's Content-Type header` - is particularly vexing!

The simplest option might be to document the limitations of IE8/9 for users, and rely on them to pass the correct options to the tire ajax api - ie allowing them to make the choice of whether to support those browsers or not.

The approach I'm taking for now can be seen below. It handles IE8/9, but in a fairly rudimentary way by creating another interface for cross-origin requests. It is basically a clone of the `tire#ajax` api except with no support for setting headers, contentType, etc and it sets the Content-Type to the proper value.

```
(function ($) {
  // adapted: http://www.leggetter.co.uk/2010/03/12/making-cross-domain-javascript-requests-using-xmlhttprequest-or-xdomainrequest.html
  function crossSiteAjax(url, options) {
    var isIE8 = window.XDomainRequest ? true : false
      , invocation = createCrossDomainRequest()
      , method = (options.type || 'GET').toUpperCase()
      , params = options.data || null
      , success = options.success || function(){}
      , failure = options.failure || function(){};

    function createCrossDomainRequest() {
      var request;
      if (isIE8) {
        request = new window.XDomainRequest();
      }
      else {
        request = new XMLHttpRequest();
      }
      return request;
    }

    function executeRequest() {
      if (invocation) {
        if(isIE8) {
          // https://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx?Redirected=true
          invocation.onload = ieHandler;
          invocation.open(method, url, true);
          if (options.data && method !== 'GET') {
            invocation.setRequestHeader('Content-Type', 'text/plain');
          }
          invocation.send(tire.param(params));
        }
        else {
          invocation.open(method, url, true);
          if (options.data && method !== 'GET') {
            invocation.setRequestHeader('Content-Type', (options.contentType || 'application/x-www-form-urlencoded'));
          }
          invocation.onreadystatechange = modernHandler;
          invocation.send(tire.param(params));
        }
      }
      else {
        console.log("Could not send request.")
      }
    }

    function modernHandler(evtXHR) {
      if (invocation.readyState == 4) {
        if (invocation.status == 200) {
            ajaxSuccess(invocation);
        } else {
          failure();
        }
      }
    }

    function ieHandler() {
      ajaxSuccess(invocation);
    }

    function ajaxSuccess(xhr) {
      var res;
      if (xhr) {
        try {
          res = tire.parseJSON(xhr.responseText)
        }
        catch (e) {
          res = xhr.responseText;
        }
      }
      if (tire.isFunction(success)) success(res);
    }

    executeRequest();
  }

  $.extend($, { crossSiteAjax: crossSiteAjax });
}(tire));
```

**Comment by caromill** [comment]
@jkonowitch Thank you for your answer. We agree that it definitely is valuable to be able to say that we provide IE8/9 support for all features. As you showed, it will require some workarounds in the code as well as an explanation to its limitations in the documentation. Our main concern is that all those workarounds will increase the size. That said, we have plans to make Tire modular (a bit further down the line) to provide the ability to choose the parts you need. In the meanwhile we are considering doing a plugin that will contain CORS for all the browsers we support. Does that sound like a viable option?

**Comment by jkonowitch** [comment]
Ah - this does conflict with another really important design goal - size! There are no easy answers huh? :) (though that's what makes this fun)

I think the plugin/modular approach is a great one; let the end user decide whether she needs the added functionality. My guess is that CORS support (especially back to IE8/9) isn't necessarily in huge demand; the most common use case for xhr is to communicate with one's own server. Allowing users to plugin support if needed satisfies many of Tire.js's design goals: to be compatible with the most used browsers back to IE8/9, to be simple, and to be very lightweight.

**Comment by caromill** [comment]
@jkonowitch Perfect. One CORS plugin coming right up then. Well, sort of.

**Comment by jkonowitch** [comment]
:)

**Comment by caromill** [comment]
Hey @jkonowitch, now that Tire 1.2.0 is released you can take a look at the [tire.cors.js](https://github.com/tirejs/tire-cors) plugin. Love to hear what you think about it. We will soon promote it on the web site as well.

**Comment by jkonowitch** [comment]
Nice work! And it works well as a plugin. Thanks for your hard work :)
