### ISSUE TITLE
Feature Request, async: false

### ISSUE THREAD

**Issue by utroda** [tirejs/tire#23]
Is there anyway of getting the jQuery feature of setting async to false, on ajax calls?

**Comment by smcmurray** [comment]
From http://tirejs.com/#ajax/ajax

> No sync request is supported and no support is planned.

**Comment by frozzare** [comment]
There are no plans for that right now. I don't have any problems with a fork that adds this support (I'm happy to help with this) and maybe in the feature add that fork to the core.

**Comment by utroda** [comment]
Thanks for the info, I must have just looked over it in the docs.
