### ISSUE TITLE
Issue - Delegated Event

### ISSUE THREAD

**Issue by utroda** [tirejs/tire#26]
The following fires on any click within the body element, not just on anchor elements.

``` javascript
$(document.body).on('click', 'a', function(e){
    e.preventDefault();
   console.log(e);
});
```

**Comment by frozzare** [comment]
Yes, this is a bug. Thanks for reporting it.

**Comment by frozzare** [comment]
Created a new branch with a fix for this, would you like to try it? https://github.com/tirejs/tire/tree/next

Created two simple tests, the first with no html just Tire and with your JavaScript example. It don't logging any to console. See http://jsfiddle.net/4653z/embedded/result/ (open inspector).

The second test I added a anchor element, if you click the anchor element it starts to log to console.
http://jsfiddle.net/QNjn8/1/embedded/result/

**Comment by utroda** [comment]
The fiddles look good, I will download that branch a bit later and give it a test.

## 

Jared West
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by frozzare** [comment]
ping @utroda

**Comment by utroda** [comment]
Sorry man, I have been super busy lately, I will try and take a look today.

## 

Jared West
Interaction Designer / Front-End Developer
www.wearedifrnt.com
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by utroda** [comment]
Looks like everything is good, sorry for the delay. Again thanks for the quick fix.
