### ISSUE TITLE
Issue - Posting JSON data

### ISSUE THREAD

**Issue by crowl** [tirejs/tire#27]
When posting JSON like this:

``` javascript
var someData = {
    foo: 'bar'
};

$.ajax({
    type: 'POST',
    url: '/something'
    contentType: 'application/json',
    data: JSON.stringify(someData),
    success: function(d) { 
        console.log(d);
    }
});
```

The JSON string gets passed to `tire.param()`, and the request fails because of invalid JSON, even though I specified the content type as JSON.

**Comment by frozzare** [comment]
Pushed a fix for this, you are welcome to try it out. Waiting on #26 before I will release the minor bug fix release of Tire.

**Comment by crowl** [comment]
Everything looks fine now, thanks
