### ISSUE TITLE
Toggle() not working, and trim() should rely on native code

### ISSUE THREAD

**Issue by ghost** [tirejs/tire#28]
Toogle() not working. It only make the div tag visible, but not hiding it again.

Trim() should rely on the native trim() if possible, much faster. See angular.js as an example on this.

**Comment by frozzare** [comment]
Have you an example where toggle isn't working? I did test it and it works, see http://jsfiddle.net/J4dq4/

Trim is using the native trim if it exists.

**Comment by ghost** [comment]
Hi

I see it's working there. Don't have a example by hand because the system I
develop is to complex, but I tried to remember what could trigger this. In
my case I use a unsorted list. I tested the more complex solution in
jsfiddle now and there it works- strange: http://jsfiddle.net/J4dq4/1/.

Another situation it does not work is if you have an JSON array. Say you
have an JSON array and you have a button that let you navigate, and
everytime you click the content of a div tag is changed and new content is
extracted from the JSON array, and made visible inside the div tag without
pageload. If each new content have a div tag that should activate a
toggle() function, only the div tag that is visible in the moment you do a
page load will toggle(). If you browse, the toggle() function is not
working on the other divs that will be visible. It does not remember the
"state". I tried ofc to use .on() here but not working.

**Comment by ghost** [comment]
The JSON problem I mentioned are not there in JQUERY. If you look at how
the .on() function is working there you understand.

$("body").on("click", ".tt", function (e) { })

The element is bound to the document body

**Comment by frozzare** [comment]
It would be useful if you give a live example of the things that aren't working. Some stuff in jQuery will not working in Tire, you can't build a complex site with jQuery and switch to Tire. Stuff will break and that's how it will be. Closing this issue since there aren't any example of stuff not working. And the jsfiddle I did present did work.
