### ISSUE TITLE
Code is slow, and no variable caching

### ISSUE THREAD

**Issue by ghost** [tirejs/tire#29]
I was reading through your code now, and noticed there is no variable caching - something that slow down this script.  Look at this function:

 find: function ()

a lot of this. The code would be faster if you cached the variable with var _this = this and use _this.

Use of try {} catch also slow down this code, and there is more into it. I just scratched the surface here

**Comment by frozzare** [comment]
You're welcome to submit pull requests with fixes like this since I don't develop Tire so much more then fixing bugs and so.

**Comment by ghost** [comment]
There is to much strange things in this code to make pullrequests. I
compared with a lot of libs too.  The speed here is a critical issue.

Im working on a solution btw. But have to re-write.

Feel free to send private mail and I can inform further.
13. nov. 2013 21:31 skrev "Fredrik Forsmo" notifications@github.com
følgende:
