### ISSUE TITLE
Using grunt-cli

### ISSUE THREAD

**Issue by webpro** [tirejs/tire#6]
Since I'm using grunt-cli (grunt v0.4), when I wanted to try and build tire I got a 

> [..] Fatal error: Unable to find local grunt.

This is a possible fix:

```
npm install grunt --save-dev
```

An explanation could be added to the docs. Another option is to always assume a local version of grunt (by adding e.g. `"grunt": "~0.3.17"` to `devDependencies` in package.json upfront) and adapt the Makefile to that.

Also see some [grunt docs](https://github.com/gruntjs/grunt/wiki/Getting-started).

**Comment by frozzare** [comment]
I think adding `"grunt": "~0.3.17"` is the best option and change the Makefile and .travis.yml (since we don't need to install grunt two times).
