### ISSUE TITLE
How to actually run tests in docs

### ISSUE THREAD

**Issue by webpro** [tirejs/tire#7]
Might be obvious, but there's no line explaining how to run tests in the readme, e.g.

> Then run `grunt qunit`, or open `test/index.html` in your browser to run the tests.

**Comment by webpro** [comment]
Btw, the command `make test` is not running tests, so perhaps this should be extended or renamed.

**Comment by webpro** [comment]
Opening `http://localhost:3000/` to run tests is an option as well apparently :-)

**Comment by frozzare** [comment]
Will remove `make test` since it's not necessary. Should add a sentence to the readme that describes that you should open `http://localhost:3000/` to run the tests.
